typography_spectrum: 0.5680851
color:
  saturation: 0.4765958
  brandStrength: 0.6255319
  rhythmicContrast: 0.4148936
  brandColors:
    - '#C6994B'
    - '#C6C7C6'
    - '#92A36E'
    - '#5E5241'
    - '#777680'
  lightness: 0.4659574
layout_spectrum: 0.5893617
author:
  name: ROBERT BISCOE
  email: robert@biscoewilson.com.au
  url: www.biscoewilson.com.au
name: biscoewilson|architects
navigation:
  - name: About Biscoe Wilson Architects
    url: www.biscoewilson.com.au
    type: external
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
